language: python
python:
    - "2.7"
    
sudo: false
cache:
    directories:
        - "~/.platformio"
    
env:
    - PLATFORMIO_CI_SRC=examples/SL06_Ambient_Light.ino
    - PLATFORMIO_CI_SRC=examples/SL06_Color.ino
    - PLATFORMIO_CI_SRC=examples/SL06_Gesture.ino
    - PLATFORMIO_CI_SRC=examples/SL06_Proximity.ino

install:
    - pip install -U platformio
    - platformio update

    - wget https://github.com/xinabox/arduino-CORE/archive/master.zip -O /tmp/arduino-CORE.zip
    - unzip /tmp/arduino-CORE.zip -d /tmp/

script:
    - platformio ci --lib="." --lib="/tmp/arduino-CORE-master" --board=uno --board=zero --board=xinabox_cw01 --board=xinabox_cw02
